error_generation_config:
  drop_prob: .33
  counter_spike_prob: .33
  status_flip_prob: .33
  counter_zero_prob: .33
  delay_prob: .33
  delay_mean: 40.0
  delay_var: 10.0
  delay_min: 20.0

telemetry_config:
  # logging_dir: "/home/mininet/input-validation/.logout"
  base_log_dir: "/home/mininet/experiment-out/base"
  error_log_dir: "/home/mininet/experiment-out/error"
  collection_interval: 10
  base_log_prefix: "base_telemetry"
  error_log_prefix: "error_telemetry"
  max_rows: 500
  ignore_bad_flow_parsing: True

topology_config:
  # logging_dir: "/home/mininet/input-validation/.logout"
  use_bw_delay: True
  naive_link_bw: 10000
  naive_link_delay: 25
  
  use_naive_bw: True
  use_naive_delay: False

  topohub_name: "sndlib/newyork"
  graph_file_path: None
  networkx_graph_read_function: None
  mininet_topo_path: None

  topohub_mean_link_delay: 25
  hosts_per_switch: 2

network_event_config:
  event_interrarival_mean: 10

traffic_generation_config:
  # logging_dir: "/home/mininet/input-validation/.logout"
  flow_bandwidth_min: 2
  flow_bandwidth_mean: 8
  flow_bandwidth_var: 5

  flow_duration_min: 5
  flow_duration_mean: 10
  flow_duration_var: 3

  flows_per_host: 1

  total_bandwidth_limit: 3000
  total_stream_limit: 100

  error_on_stream_failure: False

experiment_config:
  # logging_dir: "/home/mininet/input-validation/.logout"
  experiment_time_mins: 1
  logging_config_filepath: "/home/mininet/input-validation/log_config.yaml"