version: 1
formatters:
  verbose_singlethread:
    format: '%(levelname)s %(asctime)s %(name)s at %(filename)s:%(funcName)s:%(lineno)d: %(message)s'
  verbose_multithread:
    format: '%(levelname)s %(asctime)s %(name)s, process %(process)d:%(thread)d at 
%(filename)s:%(funcName)s:%(lineno)d: %(message)s'
  simple_singlethread: 
    format: '%(levelname)s %(asctime)s %(name)s: %(message)s'
  simple_multithread: 
    format: '%(levelname)s %(asctime)s %(name)s, process %(process)d:%(thread)d: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: NOTSET
    formatter: verbose_multithread
    stream: ext://sys.stdout
  experiment_main_file:  
    class : logging.FileHandler
    filename: /home/mininet/experiment-out/experiment_main_logging.txt
    mode: "a"
    formatter: verbose_multithread
  telemetry_file:  
    class : logging.FileHandler
    filename: /home/mininet/experiment-out/telemetry_logging.txt
    mode: "a"
    formatter: verbose_multithread
  topology_file:  
    class : logging.FileHandler
    filename: /home/mininet/experiment-out/topology_logging.txt
    mode: "a"
    formatter: verbose_multithread
  traffic_generation_file:  
    class : logging.FileHandler
    filename: /home/mininet/experiment-out/traffic_generation_logging.txt
    mode: "a"
    formatter: verbose_multithread
  
loggers:
  experiment_main:
    level: DEBUG
    handlers: [console, experiment_main_file]
    propagate: no
  telemetry_collection:
    level: DEBUG
    handlers: [console, telemetry_file]
    propagate: no
  topology:
    level: DEBUG
    handlers: [console, topology_file]
    propagate: no
  traffic_generation:
    level: DEBUG
    handlers: [console, traffic_generation_file]
    propagate: no
root:
  level: NOTSET
  handlers: [console]