version: 1
formatters:
  verbose_singlethread:
    format: '%(levelname)s %(asctime)s %(name)s at
%(filename)s:%(funcName)s:%(lineno)d: %(message)s'
  verbose_multithread:
    format: '%(levelname)s %(asctime)s %(name)s, process %(process)d:%(thread)d at 
%(filename)s:%(funcName)s:%(lineno)d: %(message)s'
  simple_singlethread: '%(levelname)s %(asctime)s %(name)s: %(message)s'
  simple_multithread: '%(levelname)s %(asctime)s %(name)s, process %(process)d:%(thread)d: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: NOTSET
    formatter: verbose_multithread
    stream: ext://sys.stdout
  # telemetry_file:  
  #   class : logging.handlers.FileHandler
  #   formatter: precise
  #   filename: 
  #   maxBytes: 1024
  #   backupCount: 3
  
loggers:
  experiment_main:
    level: DEBUG
    handlers: [console]
    propagate: no
  telemetry_collection:
    level: DEBUG
    handlers: [console]
    propagate: no
  topology:
    level: DEBUG
    handlers: [console]
    propagate: no
  traffic_generation:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: NOTSET
  handlers: [console]